# Generated by Django 3.0.4 on 2020-05-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='account',
        ),
    ]
