# Generated by Django 3.0.6 on 2020-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200522_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='takeACT',
            field=models.BooleanField(default=False, verbose_name='is ACT'),
        ),
        migrations.AddField(
            model_name='account',
            name='takeIELTS',
            field=models.BooleanField(default=False, verbose_name='is IELTS'),
        ),
        migrations.AddField(
            model_name='account',
            name='takeSAT',
            field=models.BooleanField(default=False, verbose_name='is SAT'),
        ),
        migrations.AddField(
            model_name='account',
            name='takeTOEFL',
            field=models.BooleanField(default=False, verbose_name='is TOEFL'),
        ),
    ]
